import UIKit

struct CalculationData {
    static let chinaLocations = ["Anji (Zhejiang)", "Anlu (Hubei)", "Anping (Hebei)", "Anqing (Anhui)", "Anshan (Liaoning)", "Anyang (Henan)", "Baoding (Hebei)", "Baoshan (Shanghai)", "Baoying (Jiangsu)", "Beijing (Beijing)", "Bengbu (Anhui)", "Benxi (Liaoning)", "Binhai (Jiangsu)", "Binzhou (Shandong)", "Cangzhou (Hebei)", "Changde (Hunan)", "Changshu (Jiangsu)", "Chanzhou (Jiangsu)", "Chaoyang (Liaoning)", "Chaozhou (Guangdong)", "Chizhou (Anhui)", "Chongqing (Chongqing)", "Cixi (Zhejiang)", "Dalian (Liaoning)", "Dandong (Liaoning)", "Danyang (Jiangsu)", "Deqing (Zhejiang)", "Dezhou (Shandong)", "Dingzhou (Hebei)", "Dongguan (Guangdong)", "Dongyang (Zhejiang)", "Dongying (Shandong)", "Fengxian (Shanghai)", "Foshan (Guangdong)", "Fuan (Fujian)", "Fuxin (Liaoning)", "Fuyang (Zhejiang)", "Fuyang (Anhui)", "Fuzhou (Fujian)", "Guangzhou (Guangdong)", "Haiyan (Zhejiang)", "Handan (Hebei)", "Hangzhou (Zhejiang)", "Hebi (Henan)", "Hefei (Anhui)", "Heze (Shandong)", "Huaian (Jiangsu)", "Huangshan (Anhui)", "Huizhou (Guangdong)", "Huludao (Liaoning)", "Huzhou (Zhejiang)", "Jiading (Shanghai)", "Jiande (Zhejiang)", "Jiangmen (Guangdong)", "Jiangyan (Jiangsu)", "Jiangying (Jiangsu)", "Jiaozuo (Henan)", "Jiashan (Zhejiang)", "Jiaxing (Zhejiang)", "Jinan (Shandong)", "Jincheng (Shanxi)", "Jinhu (Jiangsu)", "Jinhua (Zhejiang)", "Jining (Shandong)", "Jinjiang (Fujian)", "Jinshan (Shanghai)", "Jintan (Jiangsu)", "Jinzhou (Liaoning)", "Jurong (Jiangsu)", "Kaifeng (Henan)", "Kunshan (Jiangsu)", "Langfang (Hebei)", "Lianyungang (Jiangsu)", "Liaocheng (Shandong)", "Liaoyang (Liaoning)", "Linan (Zhejiang)", "Linqing (Shandong)", "Linyi (Shandong)", "Lishui (Zhejiang)", "Liuan (Anhui)", "Liyang (Jiangsu)", "Longyan (Fujian)", "Luoyang (Henan)", "Maanshan (Anhui)", "Maoming (Guangdong)", "Nanjing (Jiangsu)", "Nanping (Fujian)", "Nantong (Jiangsu)", "Nanyang (Henan)", "Ningbo (Zhejiang)", "Ningde (Fujian)", "Panjin (Liaoning)", "Pinghu (Zhejiang)", "Pudong (Shanghai)", "Putian (Fujian)", "Qidong (Jiangsu)", "Qingdao (Shandong)", "Qinhuangdao (Hebei)", "Quanzhou (Fujian)", "Quzhou (Zhejiang)", "Rizhao (Shandong)", "Rugao (Jiangsu)", "Sanmenxia (Henan)", "Sanming (Fujian)", "Shangqiu (Henan)", "Shangyu (Zhejiang)", "Shantou (Guangdong)", "Shaoguan (Guangdong)", "Shaoxing (Zhejiang)", "Shenyang (Liaoning)", "Shenzhen (Guangdong)", "Shijiazhuang (Hebei)", "Shishi (Fujian)", "Shiyan (Hubei)", "Songjiang (Shanghai)", "Suqian (Jiangsu)", "Suzhou (Jiangsu)", "Taian (Shandong)", "Taicang (Jiangsu)", "Taizhou (Jiangsu)", "Taizhou (Zhejiang)", "Tanshan (Hebei)", "Tengzhou (Shandong)", "Tianjin (Tianjin)", "Tongling (Anhui)", "Tonglu (Zhejiang)", "Weifang (Shandong)", "Weihai (Shandong)", "Wenling (Zhejiang)", "Wenzhou (Zhejiang)", "Wuhu (Anhui)", "Wujiang (Jiangsu)", "Wushun (Liaoning)", "Wuxi (Jiangsu)", "Wuzhou (Zhejiang)", "Xiamen (Fujian)", "Xian (Shanxi)", "Xiaoshan (Zhejiang)", "Xingtai (Hebei)", "Xinxiang (Henan)", "Xinyang (Henan)", "Xuancheng (Anhui)", "Xuzhou (Jiangsu)", "Yancheng (Jiangsu)", "Yangzhou (Jiangsu)", "Yantai (Shandong)", "Yingkou (Liaoning)", "Yiwu (Zhejiang)", "Yixing (Jiangsu)", "Yueqing (Zhejiang)", "Yunfu (Guangdong)", "Yuyao (Zhejiang)", "Zaozhuang (Shandong)", "Zhangjiagang (Jiangsu)", "Zhangjiakou (Hebei)", "Zhangzhou (Fujian)", "Zhanjiang (Guangdong)", "Zhengzhou (Henan)", "Zhenjiang (Jiangsu)", "Zhongshan (Guangdong)", "Zhoukou (Henan)", "Zhoushan (Zhejiang)", "Zhuhai (Guangdong)", "Zhuji (Zhejiang)", "Zhumadian (Henan)", "Zhuzhou (Hunan)", "Zibo (Shandong)"]
    
    static let turkeyLocations = ["Adana (01110)", "Ankara (06980)", "Antalya (07070)", "Aydın (09000)", "Balıkesir (10100)", "Bursa (16450)", "Corlu (59850)", "Denizli (20040)", "Düzce (81100)", "Eskişehir (26000)", "Gaziantep (27620)", "Gebze (41400)", "Gemlik (16600)", "Hatay (31000)", "Istanbul (-)", "Izmir (35220)", "Kayseri (38170)", "Kazan (06000)", "Kahramanmaraş (46140)", "Kocaeli (İzmit) (41200)", "Konya (42160)", "Malatya (44000)", "Manisa (45110)", "Mersin (33060)", "Muğla (48000)", "Sakarya (54580)", "Tekirdağ (59000)", "Yalova (77200)"
    ]
    
    static let categories = [
        (title: "Авто-аксессуары", subtitle: "Cигнализации, автомагнитолы и т.д."),
        (title: "Автозапчасти", subtitle: ""),
        (title: "Аксессуары (одежда)", subtitle: "Перчатки, галстуки, шарфы, платки, гол.уборы"),
        (title: "Бельё", subtitle: ""),
        (title: "Аксессуары", subtitle: ""),
        (title: "Антенны", subtitle: "И аксессуары"),
        (title: "Бассейны, сауны, бани", subtitle: "Оборудование и аксессуары"),
        (title: "Бижутерия", subtitle: ""),
        (title: "Браслеты, ремешки, футляры", subtitle: "Для часов"),
        (title: "Бисер", subtitle: ""),
        (title: "Бытовые клеи", subtitle: "Красители и др."),
        (title: "Бытовые насосы", subtitle: "Шланги"),
        (title: "Гладильные доски", subtitle: "Сушилки для белья, стремянки"),
        (title: "Бытовая техника", subtitle: "И электроника"),
        (title: "Галантерея", subtitle: "Нитки, кошельки, ремни, сумки и пр."),
        (title: "Бытовая мебель для дома", subtitle: "Мягкая мебель, спальни"),
        (title: "Бытовая химия", subtitle: ""),
        (title: "Конструкции для строительства", subtitle: "Готовые и разборные"),
        (title: "Детская мебель", subtitle: ""),
        (title: "Декоративная косметика", subtitle: ""),
        (title: "Душевые и паровые кабины", subtitle: "Гидромассажные ванны"),
        (title: "Детская одежда", subtitle: ""),
        (title: "Детская обувь", subtitle: ""),
        (title: "Елочные украшения", subtitle: "Новогодние и другие праздничные товары"),
        (title: "Дачная и кемпинговая мебель", subtitle: ""),
        (title: "Декоративные изделия", subtitle: "Картины, постеры, эстампы, фонтаны и др."),
        (title: "Домофоны", subtitle: ""),
        (title: "Игровое оборудование", subtitle: ""),
        (title: "Зеркала", subtitle: ""),
        (title: "Жалюзи", subtitle: "Карнизы, портьеры, шторы"),
        (title: "Запчасти ", subtitle: "Комплектующие к производственному оборудованию"),
        (title: "Запчасти", subtitle: "К торговому оборудованию"),
        (title: "Замочные изделия", subtitle: "Оконная и дверная фурнитура"),
        (title: "Игрушки", subtitle: "Конструкторы, настольные игры и др."),
        (title: "Канцтовары", subtitle: "Книги, школьные принадлежности"),
        (title: "Инструменты", subtitle: ""),
        (title: "Измерительный инструмент", subtitle: "И приборы"),
        (title: "Климатическое оборудование", subtitle: "Кондиционеры, системы вентиляции, увлажнители, осушители и их комплектующие"),
        (title: "Кладочные материалы", subtitle: "Кирпич, камень, блоки"),
        (title: "Керамическая плитка", subtitle: "Отделочный камень"),
        (title: "Книги", subtitle: "Журналы и другая печатная продукция"),
        (title: "Отопительное оборудование", subtitle: ""),
        (title: "Кожа натуральная", subtitle: ""),
        (title: "Кожзаменители", subtitle: ""),
        (title: "Ковры", subtitle: "Ковровые изделия"),
        (title: "Косметические принадлежности", subtitle: "Маникюрные, бритвенные"),
        (title: "Компьютерные товары", subtitle: ""),
        (title: "Компьютеры, ноутбуки", subtitle: ""),
        (title: "Косметика", subtitle: "Парфюмерия"),
        (title: "Крепежные изделия", subtitle: "Метизы, фитинги"),
        (title: "Крупная бытовая техника", subtitle: "Холодильники, стиральные машины, плиты, вытяжки и др."),
        (title: "Кухонная мебель", subtitle: ""),
        (title: "Лакокрасочные материалы", subtitle: "Клеи, герметики, антисептики"),
        (title: "Люстры", subtitle: "Торшеры, бра, плафоны бытовые и комплектующие"),
        (title: "Тара и упаковка", subtitle: ""),
        (title: "Материалы для производства", subtitle: "Полиэтилен, листы пластмассы, бумаги"),
        (title: "Масла", subtitle: "Смазки, автокосметика"),
        (title: "Мангалы", subtitle: "Барбекю, грили, коптильни и принадлежности"),
        (title: "Мебель для ресторанов", subtitle: ""),
        (title: "Мебельная фурнитура", subtitle: "Аксессуары и комплектующие"),
        (title: "Медицинское оборудование", subtitle: ""),
        (title: "Мебель", subtitle: ""),
        (title: "Медицинский комплект", subtitle: ""),
        (title: "Мебель и аксессуары", subtitle: "Для ванных комнат"),
        (title: "Мелкая бытовая техника", subtitle: "Пылесосы, обогреватели, утюги, фены, чайники, кофеварки и др."),
        (title: "Мелкая кожгалантерея", subtitle: "Кошельки, ремни"),
        (title: "Меховые изделия", subtitle: "Шубы, дубленки, муфты, шапки меховые"),
        (title: "Механический инструмент", subtitle: ""),
        (title: "Металлопрокат", subtitle: "Арматура, проволока, сетка"),
        (title: "Навигационные приборы", subtitle: "И оборудование"),
        (title: "Мото- и квадроциклы", subtitle: "Снегоходы"),
        (title: "Музыкальные инструменты", subtitle: "И принадлежности"),
        (title: "Напольные покрытия", subtitle: "Паркет, линолеум, ковролин"),
        (title: "Оборудование, станки", subtitle: "Для металлообрабатывающего и машиностроительного производства"),
        (title: "Оборудование и инвентарь", subtitle: "Для торговли"),
        (title: "Оборудование", subtitle: "Для пищевой промышленности"),
        (title: "Средства связи", subtitle: "И оборудование"),
        (title: "Обои", subtitle: "Самоклеящаяся пленка"),
        (title: "Обувь", subtitle: ""),
        (title: "Оборудование для отопления", subtitle: "Печи, радиаторы"),
        (title: "Оборудование торговое", subtitle: "весы, кассовые аппараты, штрих коды и т.д."),
        (title: "Полиграфическая продукция", subtitle: "Открытки, календари"),
        (title: "Ограждения, ворота", subtitle: "Решетки, ставни, кованые изделия"),
        (title: "Офисная техника", subtitle: ""),
        (title: "Одежда", subtitle: ""),
        (title: "Охранное оборудование", subtitle: "И аксессуары"),
        (title: "Окна, двери", subtitle: "Перегородки"),
        (title: "Офисная мебель", subtitle: ""),
        (title: "Оборудование охранное", subtitle: "И противопожарное"),
        (title: "Пластиковая мебель", subtitle: ""),
        (title: "Парфюмерия", subtitle: ""),
        (title: "Парики", subtitle: "Шиньоны, накладки"),
        (title: "Предметы интерьера", subtitle: ""),
        (title: "Подарочная упаковка", subtitle: ""),
        (title: "Посуда", subtitle: ""),
        (title: "Постельные принадлежности", subtitle: "Полотенца, скатерти и др."),
        (title: "Пневмоинструмент", subtitle: "И гидроинструмент"),
        (title: "Прочая галантерея", subtitle: ""),
        (title: "Продукты питания", subtitle: "В потребительской упаковке"),
        (title: "Промышленная химия", subtitle: ""),
        (title: "Оборудование промышленное", subtitle: "И производственное"),
        (title: "Противопожарное оборудование", subtitle: "И аксессуары"),
        (title: "Провода, кабели", subtitle: ""),
        (title: "Прочая бытовая химия", subtitle: ""),
        (title: "Прочая бытовая техника", subtitle: ""),
        (title: "Прочая косметика", subtitle: ""),
        (title: "Прочее торговое оборудование", subtitle: ""),
        (title: "Прочие инструменты", subtitle: ""),
        (title: "Прочее клим. оборудование", subtitle: ""),
        (title: "Прочие отделочные материалы", subtitle: ""),
        (title: "Прочая сантехника", subtitle: ""),
        (title: "Прочие канцтовары", subtitle: ""),
        (title: "Прочие предметы интерьера", subtitle: ""),
        (title: "Прочие товары для детей", subtitle: ""),
        (title: "Прочий текстиль", subtitle: ""),
        (title: "Расходники", subtitle: "Материалы, аксессуары, запчасти, комплектующие к инструментам"),
        (title: "Рекламные материалы", subtitle: "И оборудование (стенды)"),
        (title: "Пряжа", subtitle: ""),
        (title: "Прочие хоз.товары", subtitle: ""),
        (title: "Транспортные средства", subtitle: "Самоходные наземные"),
        (title: "Рыболовные товары", subtitle: ""),
        (title: "Охотничьи товары", subtitle: ""),
        (title: "Санфаянс", subtitle: "Ванны, раковины, унитазы и др."),
        (title: "Садовая техника", subtitle: "Оборудование и инвентарь"),
        (title: "Сантехника", subtitle: ""),
        (title: "Складское оборудование", subtitle: "И инвентарь"),
        (title: "Смесители", subtitle: "Краны, вентили, трубы, фитинги"),
        (title: "Сейфы", subtitle: ""),
        (title: "Средства ухода за кожей", subtitle: "Туалетное мыло, товары для душа, крема"),
        (title: "Средства радио связи", subtitle: ""),
        (title: "Спортивное питание", subtitle: ""),
        (title: "Стиральные порошки", subtitle: "Чистящие и моющие средства"),
        (title: "Спортивная экипировка", subtitle: "Одежда, обувь"),
        (title: "Средства мобильной связи", subtitle: "И аксессуары"),
        (title: "Спортинвентарь", subtitle: "Велосипеды, коньки, лыжи и др."),
        (title: "Приборы", subtitle: "Телекоммуникационные и навигационные"),
        (title: "Панели", subtitle: "Стеновые и отделочные, потолки"),
        (title: "Солнцезащитные очки", subtitle: ""),
        (title: "Столовые приборы", subtitle: "Кухонный инвентарь"),
        (title: "Сумки", subtitle: "Чемоданы, портфели"),
        (title: "Строительное оборудование", subtitle: ""),
        (title: "Сварочное оборудование", subtitle: ""),
        (title: "Отделочные материалы", subtitle: "Конструкции и крепежи"),
        (title: "Сыпучие строй материалы", subtitle: "щебень, песок и др."),
        (title: "Тара, упаковка", subtitle: ""),
        (title: "Гидроизоляционные материалы", subtitle: "Тепло-, шумо-"),
        (title: "Сырье", subtitle: "Для производства бытовой химии"),
        (title: "Текстильные изделия", subtitle: ""),
        (title: "Кисти, краски", subtitle: "Товары для художественного творчества"),
        (title: "Ткани", subtitle: ""),
        (title: "Товары для отдыха", subtitle: "Спорта, охоты, рыбалки"),
        (title: "Швейные товары", subtitle: "Для швейного и прядильного производства"),
        (title: "Термоинструмент", subtitle: "Строительные фены, паяльные лампы, паяльники и др."),
        (title: "Товары для детей", subtitle: "Манежи, коляски, кровати и др."),
        (title: "Медицинские товары", subtitle: ""),
        (title: "Туалетная бумага", subtitle: "Бумажные салфетки и полотенца"),
        (title: "Тренажеры", subtitle: ""),
        (title: "Туристическое снаряжение", subtitle: "И инвентарь"),
        (title: "Фурнитура для одежды", subtitle: "Клепки, молнии, этикетки и т.д"),
        (title: "Пищевая пленка", subtitle: ""),
        (title: "Оптические приборы", subtitle: "И принадлежности"),
        (title: "Измерительные приборы", subtitle: "Весы, термометры, барометры и др."),
        (title: "Хозяйственно-бытовые товары", subtitle: ""),
        (title: "Швейные машины", subtitle: "Вязальные машины, оверлоки"),
        (title: "Чулки", subtitle: "Чулочно-носочные изделия"),
        (title: "Электротовары", subtitle: ""),
        (title: "Часы", subtitle: ""),
        (title: "Электроинструмент", subtitle: ""),
        (title: "Электрооборудование", subtitle: "Лампы"),
        (title: "Электротехнические изделия", subtitle: "Розетки, терморегуляторы и т.д."),
        (title: "Оборудование электрощитовое", subtitle: "")
    ]
    
    static let currencyOptions = [
        UIMenuItem(title: "Рубли", titleForButton: "RUB", subtitle: nil, image: UIImage(named: "RUB")),
        UIMenuItem(title: "Юани", titleForButton: "CNY", subtitle: nil, image: UIImage(named: "CNY")),
        UIMenuItem(title: "Лиры", titleForButton: "TRY", subtitle: nil, image: UIImage(named: "TRY")),
        UIMenuItem(title: "Доллары", titleForButton: "USD", subtitle: nil, image: UIImage(named: "USD")),
        UIMenuItem(title: "Евро", titleForButton: "EUR", subtitle: nil, image: UIImage(named: "EUR"))
    ]
    
    static let countriesOptions = [
        UIMenuItem(title: FLCCountryOption.china.rawValue, titleForButton: FLCCountryOption.china.rawValue, subtitle: nil, image: UIImage(named: "CNY")),
        UIMenuItem(title: FLCCountryOption.turkey.rawValue, titleForButton: FLCCountryOption.turkey.rawValue, subtitle: nil, image: UIImage(named: "TRY"))
    ]
    
    static let chinaDeliveryTypes = [
        UIMenuItem(title: "EXW", titleForButton: "EXW, Поставщик - Клиент", subtitle: "От поставщика до ваc", image: nil),
            UIMenuItem(title: "EXW", titleForButton: "EXW, Поставщик - Склад Подольск", subtitle: "От поставщика до склада FLC", image: nil),
            UIMenuItem(title: "FCA", titleForButton: "FCA, Склад Китай - Клиент", subtitle: "От склада в Китае до ваc", image: nil),
            UIMenuItem(title: "FCA", titleForButton: "FCA, Склад Китай - Склад Подольск", subtitle: "От склада в Китае до склада FLC", image: nil)
    ]
    
    static let turkeyDeliveryTypes = [
        UIMenuItem(title: "EXW", titleForButton: "EXW, Поставщик - Клиент", subtitle: "От поставщика до ваc", image: nil),
        UIMenuItem(title: "EXW", titleForButton: "EXW, Поставщик - Склад Подольск", subtitle: "От поставщика до склада FLC", image: nil),
        UIMenuItem(title: "FCA", titleForButton: "FCA, Склад Стамбул - Клиент", subtitle: "От склада в Стамбуле до ваc", image: nil),
        UIMenuItem(title: "FCA", titleForButton: "FCA, Склад Стамбул - Склад Подольск", subtitle: "От склада в Стамбуле до склада FLC", image: nil)
    ]
    
    static let russianWarehouseCity = "Подольск"
}
