import UIKit

struct CalculationInfo {
    static let chinaLocations = [
        FLCPickerItem(title: "Anji (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Anlu (Hubei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Anping (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Anqing (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Anshan (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Anyang (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Baoding (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Baoshan (Shanghai)", subtitle: "", image: nil),
        FLCPickerItem(title: "Baoying (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Beijing (Beijing)", subtitle: "", image: nil),
        FLCPickerItem(title: "Bengbu (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Benxi (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Binhai (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Binzhou (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Cangzhou (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Changde (Hunan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Changshu (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Chanzhou (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Chaoyang (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Chaozhou (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Chizhou (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Chongqing (Chongqing)", subtitle: "", image: nil),
        FLCPickerItem(title: "Cixi (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dalian (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dandong (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Danyang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Deqing (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dezhou (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dingzhou (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dongguan (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dongyang (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dongying (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Fengxian (Shanghai)", subtitle: "", image: nil),
        FLCPickerItem(title: "Foshan (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Fuan (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Fuxin (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Fuyang (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Fuyang (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Fuzhou (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Guangzhou (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Haiyan (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Handan (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Hangzhou (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Hebi (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Hefei (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Heze (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Huaian (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Huangshan (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Huizhou (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Huludao (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Huzhou (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiading (Shanghai)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiande (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiangmen (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiangyan (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiangying (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiaozuo (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiashan (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jiaxing (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jinan (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jincheng (Shanxi)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jinhu (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jinhua (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jining (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jinjiang (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jinshan (Shanghai)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jintan (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jinzhou (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Jurong (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kaifeng (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kunshan (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Langfang (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Lianyungang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Liaocheng (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Liaoyang (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Linan (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Linqing (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Linyi (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Lishui (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Liuan (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Liyang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Longyan (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Luoyang (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Maanshan (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Maoming (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Nanjing (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Nanping (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Nantong (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Nanyang (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Ningbo (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Ningde (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Panjin (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Pinghu (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Pudong (Shanghai)", subtitle: "", image: nil),
        FLCPickerItem(title: "Putian (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Qidong (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Qingdao (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Qinhuangdao (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Quanzhou (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Quzhou (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Rizhao (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Rugao (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sanmenxia (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sanming (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shangqiu (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shangyu (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shantou (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shaoguan (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shaoxing (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shenyang (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shenzhen (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shijiazhuang (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shishi (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Shiyan (Hubei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Songjiang (Shanghai)", subtitle: "", image: nil),
        FLCPickerItem(title: "Suqian (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Suzhou (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Taian (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Taicang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Taizhou (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Taizhou (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tanshan (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tengzhou (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tianjin (Tianjin)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tongling (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tonglu (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Weifang (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Weihai (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wenling (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wenzhou (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wuhu (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wujiang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wushun (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wuxi (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Wuzhou (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xiamen (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xian (Shanxi)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xiaoshan (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xingtai (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xinxiang (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xinyang (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xuancheng (Anhui)", subtitle: "", image: nil),
        FLCPickerItem(title: "Xuzhou (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yancheng (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yangzhou (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yantai (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yingkou (Liaoning)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yiwu (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yixing (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yueqing (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yunfu (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yuyao (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zaozhuang (Shandong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhangjiagang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhangjiakou (Hebei)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhangzhou (Fujian)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhanjiang (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhengzhou (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhenjiang (Jiangsu)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhongshan (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhoukou (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhoushan (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhuhai (Guangdong)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhuji (Zhejiang)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhumadian (Henan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zhuzhou (Hunan)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zibo (Shandong)", subtitle: "", image: nil)
    ]
    
    static let turkeyLocations = [
        FLCPickerItem(title: "Konya (42160)", subtitle: "", image: nil),
        FLCPickerItem(title: "Mersin (33060)", subtitle: "", image: nil),
        FLCPickerItem(title: "Adana (01110)", subtitle: "", image: nil),
        FLCPickerItem(title: "Gaziantep (27620)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kahramanmaras (46140)", subtitle: "", image: nil),
        FLCPickerItem(title: "Hatay (31000)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kayseri (38170)", subtitle: "", image: nil),
        FLCPickerItem(title: "Ankara (06980)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kazan (06000)", subtitle: "", image: nil),
        FLCPickerItem(title: "Eskisehir (26000)", subtitle: "", image: nil),
        FLCPickerItem(title: "Balikesir (10100)", subtitle: "", image: nil),
        FLCPickerItem(title: "Bursa (16450)", subtitle: "", image: nil),
        FLCPickerItem(title: "Gemlik (16600)", subtitle: "", image: nil),
        FLCPickerItem(title: "Gebze (41400)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kocaeli (Izmit) (41200)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sakarya (54580)", subtitle: "", image: nil),
        FLCPickerItem(title: "Izmir (35220)", subtitle: "", image: nil),
        FLCPickerItem(title: "Manisa (45110)", subtitle: "", image: nil),
        FLCPickerItem(title: "Denizli (20040)", subtitle: "", image: nil),
        FLCPickerItem(title: "Antalya (07070)", subtitle: "", image: nil),
        FLCPickerItem(title: "Mugla (48000)", subtitle: "", image: nil),
        FLCPickerItem(title: "Aydin (09000)", subtitle: "", image: nil),
        FLCPickerItem(title: "Malatya (44900)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tekirdag (59000)", subtitle: "", image: nil),
        FLCPickerItem(title: "Duzce (81100)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yalova (77200)", subtitle: "", image: nil),
        FLCPickerItem(title: "Corlu (59850)", subtitle: "", image: nil),
        FLCPickerItem(title: "Istanbul", subtitle: "", image: nil)
    ]
    
    static let istanbulLocations = [
        FLCPickerItem(title: "Esenyurt (34517)", subtitle: "", image: nil),
        FLCPickerItem(title: "Avcilar (34310)", subtitle: "", image: nil),
        FLCPickerItem(title: "Beylikduzu (34520)", subtitle: "", image: nil),
        FLCPickerItem(title: "Buyukcekmece (34500)", subtitle: "", image: nil),
        FLCPickerItem(title: "Catalca (34540)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kirac (34517)", subtitle: "", image: nil),
        FLCPickerItem(title: "Hadimkoy (34555)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kucukcekmece (34290)", subtitle: "", image: nil),
        FLCPickerItem(title: "Gunesli (34212)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yenibosna (34197)", subtitle: "", image: nil),
        FLCPickerItem(title: "Ikitelli (34306)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sefakoy (34295)", subtitle: "", image: nil),
        FLCPickerItem(title: "Bagcilar (34200)", subtitle: "", image: nil),
        FLCPickerItem(title: "Mahmutbey (34217)", subtitle: "", image: nil),
        FLCPickerItem(title: "Yesilkoy (34149)", subtitle: "", image: nil),
        FLCPickerItem(title: "Halkali (34303)", subtitle: "", image: nil),
        FLCPickerItem(title: "Zeytinburnu (34020)", subtitle: "", image: nil),
        FLCPickerItem(title: "Arnavutkoy (34283)", subtitle: "", image: nil),
        FLCPickerItem(title: "Bakirkoy (34140)", subtitle: "", image: nil),
        FLCPickerItem(title: "Basaksehir (34480)", subtitle: "", image: nil),
        FLCPickerItem(title: "Topkari (34093)", subtitle: "", image: nil),
        FLCPickerItem(title: "Eyup (34076)", subtitle: "", image: nil),
        FLCPickerItem(title: "Alibeykoy (34060)", subtitle: "", image: nil),
        FLCPickerItem(title: "Bayrampasa (34035)", subtitle: "", image: nil),
        FLCPickerItem(title: "Rami (34055)", subtitle: "", image: nil),
        FLCPickerItem(title: "Halic (59300)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kemerburgaz (34075)", subtitle: "", image: nil),
        FLCPickerItem(title: "Gaziosmanpasa (34250)", subtitle: "", image: nil),
        FLCPickerItem(title: "Silivri (34580)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sariyer (34450)", subtitle: "", image: nil),
        FLCPickerItem(title: "Caglayan (34403)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sutluce (34445)", subtitle: "", image: nil),
        FLCPickerItem(title: "Ayazaga (34396)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kagithane (34400)", subtitle: "", image: nil),
        FLCPickerItem(title: "Okmeydani (34384)", subtitle: "", image: nil),
        FLCPickerItem(title: "Seyrantepe (34418)", subtitle: "", image: nil),
        FLCPickerItem(title: "Maslak (34485)", subtitle: "", image: nil),
        FLCPickerItem(title: "Besiktas (34345)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tarabya (34457)", subtitle: "", image: nil),
        FLCPickerItem(title: "Etiler (34337)", subtitle: "", image: nil),
        FLCPickerItem(title: "Istinye (34460)", subtitle: "", image: nil),
        FLCPickerItem(title: "Baltalimani (34470)", subtitle: "", image: nil),
        FLCPickerItem(title: "Malkara, Tekirdag (59300)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kavacik (34810)", subtitle: "", image: nil),
        FLCPickerItem(title: "Beykoz (34820)", subtitle: "", image: nil),
        FLCPickerItem(title: "Acibadem (34460)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kozyatagi (34742)", subtitle: "", image: nil),
        FLCPickerItem(title: "Uskudar (34672)", subtitle: "", image: nil),
        FLCPickerItem(title: "Goztepe (34730)", subtitle: "", image: nil),
        FLCPickerItem(title: "Atasehir (34750)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sarigazi (34785)", subtitle: "", image: nil),
        FLCPickerItem(title: "Samandira (34885)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sultanbeyli (34920)", subtitle: "", image: nil),
        FLCPickerItem(title: "Dudullu (34773)", subtitle: "", image: nil),
        FLCPickerItem(title: "Umraniye (34760)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kartal (34876)", subtitle: "", image: nil),
        FLCPickerItem(title: "Maltepe (34844)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sancaktepe (34885)", subtitle: "", image: nil),
        FLCPickerItem(title: "Cekmekoy (34798)", subtitle: "", image: nil),
        FLCPickerItem(title: "Tuzla (34959)", subtitle: "", image: nil),
        FLCPickerItem(title: "Kurtkoy (34912)", subtitle: "", image: nil),
        FLCPickerItem(title: "Orhanli (34956)", subtitle: "", image: nil),
        FLCPickerItem(title: "Pendik (34890)", subtitle: "", image: nil),
        FLCPickerItem(title: "Gebze (41400)", subtitle: "", image: nil),
        FLCPickerItem(title: "Pelitli (41480)", subtitle: "", image: nil),
        FLCPickerItem(title: "Cayirova, Kocaeli (41435)", subtitle: "", image: nil),
        FLCPickerItem(title: "Sekerpinar, Kocaeli (41435)", subtitle: "", image: nil)
    ]
    
    static let categories: [FLCPickerItem] = [
        FLCPickerItem(title: FLCGoodsCategoryString.autoAccessories.title, subtitle: FLCGoodsCategoryString.autoAccessories.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.autoParts.title, subtitle: FLCGoodsCategoryString.autoParts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.clothingAccessories.title, subtitle: FLCGoodsCategoryString.clothingAccessories.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.underwear.title, subtitle: FLCGoodsCategoryString.underwear.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.accessories.title, subtitle: FLCGoodsCategoryString.accessories.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.antennas.title, subtitle: FLCGoodsCategoryString.antennas.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.poolsSaunasBaths.title, subtitle: FLCGoodsCategoryString.poolsSaunasBaths.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.bijouterie.title, subtitle: FLCGoodsCategoryString.bijouterie.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.braceletsStrapsCases.title, subtitle: FLCGoodsCategoryString.braceletsStrapsCases.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.beads.title, subtitle: FLCGoodsCategoryString.beads.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.householdGlues.title, subtitle: FLCGoodsCategoryString.householdGlues.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.householdPumps.title, subtitle: FLCGoodsCategoryString.householdPumps.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.ironingBoards.title, subtitle: FLCGoodsCategoryString.ironingBoards.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.householdAppliances.title, subtitle: FLCGoodsCategoryString.householdAppliances.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.haberdashery.title, subtitle: FLCGoodsCategoryString.haberdashery.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.homeFurniture.title, subtitle: FLCGoodsCategoryString.homeFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.householdChemicals.title, subtitle: FLCGoodsCategoryString.householdChemicals.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.constructionStructures.title, subtitle: FLCGoodsCategoryString.constructionStructures.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.childrensFurniture.title, subtitle: FLCGoodsCategoryString.childrensFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.decorativeCosmetics.title, subtitle: FLCGoodsCategoryString.decorativeCosmetics.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.showerAndSteamCabins.title, subtitle: FLCGoodsCategoryString.showerAndSteamCabins.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.childrensClothing.title, subtitle: FLCGoodsCategoryString.childrensClothing.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.childrensShoes.title, subtitle: FLCGoodsCategoryString.childrensShoes.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.christmasDecorations.title, subtitle: FLCGoodsCategoryString.christmasDecorations.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.gardenCampingFurniture.title, subtitle: FLCGoodsCategoryString.gardenCampingFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.decorativeItems.title, subtitle: FLCGoodsCategoryString.decorativeItems.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.intercoms.title, subtitle: FLCGoodsCategoryString.intercoms.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.playEquipment.title, subtitle: FLCGoodsCategoryString.playEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.mirrors.title, subtitle: FLCGoodsCategoryString.mirrors.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.blinds.title, subtitle: FLCGoodsCategoryString.blinds.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.spareParts.title, subtitle: FLCGoodsCategoryString.spareParts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.tradeEquipmentParts.title, subtitle: FLCGoodsCategoryString.tradeEquipmentParts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.lockProducts.title, subtitle: FLCGoodsCategoryString.lockProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.toys.title, subtitle: FLCGoodsCategoryString.toys.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.stationery.title, subtitle: FLCGoodsCategoryString.stationery.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.tools.title, subtitle: FLCGoodsCategoryString.tools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.measuringTools.title, subtitle: FLCGoodsCategoryString.measuringTools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.climateEquipment.title, subtitle: FLCGoodsCategoryString.climateEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.masonryMaterials.title, subtitle: FLCGoodsCategoryString.masonryMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.ceramicTiles.title, subtitle: FLCGoodsCategoryString.ceramicTiles.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.books.title, subtitle: FLCGoodsCategoryString.books.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.heatingEquipmentOne.title, subtitle: FLCGoodsCategoryString.heatingEquipmentOne.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.naturalLeather.title, subtitle: FLCGoodsCategoryString.naturalLeather.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.leatherSubstitutes.title, subtitle: FLCGoodsCategoryString.leatherSubstitutes.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.carpets.title, subtitle: FLCGoodsCategoryString.carpets.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.cosmeticAccessories.title, subtitle: FLCGoodsCategoryString.cosmeticAccessories.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.computerGoods.title, subtitle: FLCGoodsCategoryString.computerGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.computersLaptops.title, subtitle: FLCGoodsCategoryString.computersLaptops.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.cosmetics.title, subtitle: FLCGoodsCategoryString.cosmetics.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.fasteners.title, subtitle: FLCGoodsCategoryString.fasteners.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.largeHouseholdAppliances.title, subtitle: FLCGoodsCategoryString.largeHouseholdAppliances.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.kitchenFurniture.title, subtitle: FLCGoodsCategoryString.kitchenFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.paintMaterials.title, subtitle: FLCGoodsCategoryString.paintMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.chandeliers.title, subtitle: FLCGoodsCategoryString.chandeliers.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.packaging.title, subtitle: FLCGoodsCategoryString.packaging.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.productionMaterials.title, subtitle: FLCGoodsCategoryString.productionMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.oils.title, subtitle: FLCGoodsCategoryString.oils.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.grills.title, subtitle: FLCGoodsCategoryString.grills.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.restaurantFurniture.title, subtitle: FLCGoodsCategoryString.restaurantFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.furnitureFittings.title, subtitle: FLCGoodsCategoryString.furnitureFittings.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.medicalEquipment.title, subtitle: FLCGoodsCategoryString.medicalEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.furniture.title, subtitle: FLCGoodsCategoryString.furniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.medicalKit.title, subtitle: FLCGoodsCategoryString.medicalKit.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.bathroomFurnitureAndAccessories.title, subtitle: FLCGoodsCategoryString.bathroomFurnitureAndAccessories.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.smallHouseholdAppliances.title, subtitle: FLCGoodsCategoryString.smallHouseholdAppliances.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.smallLeatherGoods.title, subtitle: FLCGoodsCategoryString.smallLeatherGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.furProducts.title, subtitle: FLCGoodsCategoryString.furProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.mechanicalTools.title, subtitle: FLCGoodsCategoryString.mechanicalTools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.rolledMetal.title, subtitle: FLCGoodsCategoryString.rolledMetal.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.navigationInstruments.title, subtitle: FLCGoodsCategoryString.navigationInstruments.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.motorcyclesAndATVs.title, subtitle: FLCGoodsCategoryString.motorcyclesAndATVs.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.musicalInstruments.title, subtitle: FLCGoodsCategoryString.musicalInstruments.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.floorCoverings.title, subtitle: FLCGoodsCategoryString.floorCoverings.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.equipmentAndMachines.title, subtitle: FLCGoodsCategoryString.equipmentAndMachines.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.equipmentAndInventory.title, subtitle: FLCGoodsCategoryString.equipmentAndInventory.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.foodIndustryEquipment.title, subtitle: FLCGoodsCategoryString.foodIndustryEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.communicationMeans.title, subtitle: FLCGoodsCategoryString.communicationMeans.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.wallpaper.title, subtitle: FLCGoodsCategoryString.wallpaper.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.shoes.title, subtitle: FLCGoodsCategoryString.shoes.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.heatingEquipmentTwo.title, subtitle: FLCGoodsCategoryString.heatingEquipmentTwo.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.tradeEquipment.title, subtitle: FLCGoodsCategoryString.tradeEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.printedProducts.title, subtitle: FLCGoodsCategoryString.printedProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.fencesAndGates.title, subtitle: FLCGoodsCategoryString.fencesAndGates.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.officeEquipment.title, subtitle: FLCGoodsCategoryString.officeEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.clothing.title, subtitle: FLCGoodsCategoryString.clothing.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.securityEquipment.title, subtitle: FLCGoodsCategoryString.securityEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.windowsAndDoors.title, subtitle: FLCGoodsCategoryString.windowsAndDoors.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.officeFurniture.title, subtitle: FLCGoodsCategoryString.officeFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.securityAndFireEquipment.title, subtitle: FLCGoodsCategoryString.securityAndFireEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.plasticFurniture.title, subtitle: FLCGoodsCategoryString.plasticFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.perfumery.title, subtitle: FLCGoodsCategoryString.perfumery.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.wigs.title, subtitle: FLCGoodsCategoryString.wigs.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.interiorItems.title, subtitle: FLCGoodsCategoryString.interiorItems.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.giftPackaging.title, subtitle: FLCGoodsCategoryString.giftPackaging.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.dishes.title, subtitle: FLCGoodsCategoryString.dishes.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.bedding.title, subtitle: FLCGoodsCategoryString.bedding.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.pneumaticTools.title, subtitle: FLCGoodsCategoryString.pneumaticTools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherHaberdashery.title, subtitle: FLCGoodsCategoryString.otherHaberdashery.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.foodProducts.title, subtitle: FLCGoodsCategoryString.foodProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.industrialChemistry.title, subtitle: FLCGoodsCategoryString.industrialChemistry.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.industrialEquipment.title, subtitle: FLCGoodsCategoryString.industrialEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.firefightingEquipment.title, subtitle: FLCGoodsCategoryString.firefightingEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.wiresAndCables.title, subtitle: FLCGoodsCategoryString.wiresAndCables.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherHouseholdChemicals.title, subtitle: FLCGoodsCategoryString.otherHouseholdChemicals.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherHouseholdAppliances.title, subtitle: FLCGoodsCategoryString.otherHouseholdAppliances.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherCosmetics.title, subtitle: FLCGoodsCategoryString.otherCosmetics.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherTradeEquipment.title, subtitle: FLCGoodsCategoryString.otherTradeEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherTools.title, subtitle: FLCGoodsCategoryString.otherTools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherClimateEquipment.title, subtitle: FLCGoodsCategoryString.otherClimateEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherFinishingMaterials.title, subtitle: FLCGoodsCategoryString.otherFinishingMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherPlumbing.title, subtitle: FLCGoodsCategoryString.otherPlumbing.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherStationery.title, subtitle: FLCGoodsCategoryString.otherStationery.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherInteriorItems.title, subtitle: FLCGoodsCategoryString.otherInteriorItems.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherChildrenGoods.title, subtitle: FLCGoodsCategoryString.otherChildrenGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherTextiles.title, subtitle: FLCGoodsCategoryString.otherTextiles.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.consumables.title, subtitle: FLCGoodsCategoryString.consumables.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.advertisingMaterials.title, subtitle: FLCGoodsCategoryString.advertisingMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.yarn.title, subtitle: FLCGoodsCategoryString.yarn.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.otherHouseholdGoods.title, subtitle: FLCGoodsCategoryString.otherHouseholdGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.vehicles.title, subtitle: FLCGoodsCategoryString.vehicles.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.fishingGoods.title, subtitle: FLCGoodsCategoryString.fishingGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.huntingGoods.title, subtitle: FLCGoodsCategoryString.huntingGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sanitaryWare.title, subtitle: FLCGoodsCategoryString.sanitaryWare.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.gardenEquipment.title, subtitle: FLCGoodsCategoryString.gardenEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.plumbing.title, subtitle: FLCGoodsCategoryString.plumbing.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.warehouseEquipment.title, subtitle: FLCGoodsCategoryString.warehouseEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.mixers.title, subtitle: FLCGoodsCategoryString.mixers.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.safes.title, subtitle: FLCGoodsCategoryString.safes.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.skinCareProducts.title, subtitle: FLCGoodsCategoryString.skinCareProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.radioCommunicationMeans.title, subtitle: FLCGoodsCategoryString.radioCommunicationMeans.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sportsNutrition.title, subtitle: FLCGoodsCategoryString.sportsNutrition.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.laundryDetergents.title, subtitle: FLCGoodsCategoryString.laundryDetergents.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sportsEquipment.title, subtitle: FLCGoodsCategoryString.sportsEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.mobileCommunicationMeans.title, subtitle: FLCGoodsCategoryString.mobileCommunicationMeans.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sportsInventory.title, subtitle: FLCGoodsCategoryString.sportsInventory.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.instruments.title, subtitle: FLCGoodsCategoryString.instruments.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.panels.title, subtitle: FLCGoodsCategoryString.panels.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sunglasses.title, subtitle: FLCGoodsCategoryString.sunglasses.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.cutlery.title, subtitle: FLCGoodsCategoryString.cutlery.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.bags.title, subtitle: FLCGoodsCategoryString.bags.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.constructionEquipment.title, subtitle: FLCGoodsCategoryString.constructionEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.weldingEquipment.title, subtitle: FLCGoodsCategoryString.weldingEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.finishingMaterials.title, subtitle: FLCGoodsCategoryString.finishingMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.bulkBuildingMaterials.title, subtitle: FLCGoodsCategoryString.bulkBuildingMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.packagingTara.title, subtitle: FLCGoodsCategoryString.packagingTara.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.waterproofingMaterials.title, subtitle: FLCGoodsCategoryString.waterproofingMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.rawMaterials.title, subtitle: FLCGoodsCategoryString.rawMaterials.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.textileProducts.title, subtitle: FLCGoodsCategoryString.textileProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.brushesAndPaints.title, subtitle: FLCGoodsCategoryString.brushesAndPaints.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.fabrics.title, subtitle: FLCGoodsCategoryString.fabrics.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.leisureGoods.title, subtitle: FLCGoodsCategoryString.leisureGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sewingGoods.title, subtitle: FLCGoodsCategoryString.sewingGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.thermalTools.title, subtitle: FLCGoodsCategoryString.thermalTools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.childrenGoods.title, subtitle: FLCGoodsCategoryString.childrenGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.medicalGoods.title, subtitle: FLCGoodsCategoryString.medicalGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.toiletPaper.title, subtitle: FLCGoodsCategoryString.toiletPaper.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.exerciseEquipment.title, subtitle: FLCGoodsCategoryString.exerciseEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.touristEquipment.title, subtitle: FLCGoodsCategoryString.touristEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.clothingFurniture.title, subtitle: FLCGoodsCategoryString.clothingFurniture.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.foodWrap.title, subtitle: FLCGoodsCategoryString.foodWrap.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.opticalInstruments.title, subtitle: FLCGoodsCategoryString.opticalInstruments.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.measuringInstruments.title, subtitle: FLCGoodsCategoryString.measuringInstruments.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.householdGoods.title, subtitle: FLCGoodsCategoryString.householdGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.sewingMachines.title, subtitle: FLCGoodsCategoryString.sewingMachines.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.stockings.title, subtitle: FLCGoodsCategoryString.stockings.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.electricalGoods.title, subtitle: FLCGoodsCategoryString.electricalGoods.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.watches.title, subtitle: FLCGoodsCategoryString.watches.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.powerTools.title, subtitle: FLCGoodsCategoryString.powerTools.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.electricalEquipment.title, subtitle: FLCGoodsCategoryString.electricalEquipment.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.electricalProducts.title, subtitle: FLCGoodsCategoryString.electricalProducts.subtitle, image: nil),
        FLCPickerItem(title: FLCGoodsCategoryString.switchgear.title, subtitle: FLCGoodsCategoryString.switchgear.subtitle, image: nil)
    ]
    
    static let countryPhonesData = [
        FLCCountryPhonesData(countryName: String(localized: "Казахстан"), phoneCode: "+7", phoneMask: "(XXX) XXX-XX-XX", icon: UIImage(resource: .KZH), country: .kazakhstan, countryCode: "KZ"),
        FLCCountryPhonesData(countryName: String(localized: "Россия"), phoneCode: "+7", phoneMask: "(XXX) XXX-XX-XX", icon: UIImage(resource: .RUS), country: .russia, countryCode: "RU"),
        FLCCountryPhonesData(countryName: String(localized: "Афганистан"), phoneCode: "+93", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .AFG), country: .afghanistan, countryCode: "AF"),
        FLCCountryPhonesData(countryName: String(localized: "Албания"), phoneCode: "+355", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ALB), country: .albania, countryCode: "AL"),
        FLCCountryPhonesData(countryName: String(localized: "Алжир"), phoneCode: "+213", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ALG), country: .algeria, countryCode: "DZ"),
        FLCCountryPhonesData(countryName: String(localized: "Ангола"), phoneCode: "+244", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ANG), country: .angola, countryCode: "AO"),
        FLCCountryPhonesData(countryName: String(localized: "Ангилья"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ANL), country: .anguilla, countryCode: "AI"),
        FLCCountryPhonesData(countryName: String(localized: "Антигуа и Барбуда"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ANT), country: .antiguaAndBarbuda, countryCode: "AG"),
        FLCCountryPhonesData(countryName: String(localized: "Аргентина"), phoneCode: "+54", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .ARG), country: .argentina, countryCode: "AR"),
        FLCCountryPhonesData(countryName: String(localized: "Армения"), phoneCode: "+374", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .ARM), country: .armenia, countryCode: "AM"),
        FLCCountryPhonesData(countryName: String(localized: "Австралия"), phoneCode: "+61", phoneMask: "(X) XXXX-XXXX", icon: UIImage(resource: .AVS), country: .australia, countryCode: "AU"),
        FLCCountryPhonesData(countryName: String(localized: "Австрия"), phoneCode: "+43", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .AVT), country: .austria, countryCode: "AT"),
        FLCCountryPhonesData(countryName: String(localized: "Азербайджан"), phoneCode: "+994", phoneMask: "(XX) XXX-XX-XX", icon: UIImage(resource: .AZB), country: .azerbaijan, countryCode: "AZ"),
        FLCCountryPhonesData(countryName: String(localized: "Багамы"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .BGM), country: .bahamas, countryCode: "BS"),
        FLCCountryPhonesData(countryName: String(localized: "Бахрейн"), phoneCode: "+973", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .BHR), country: .bahrain, countryCode: "BH"),
        FLCCountryPhonesData(countryName: String(localized: "Барбадос"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .BAR), country: .barbados, countryCode: "BB"),
        FLCCountryPhonesData(countryName: String(localized: "Беларусь"), phoneCode: "+375", phoneMask: "(XX) XXX-XX-XX", icon: UIImage(resource: .BLR), country: .belarus, countryCode: "BY"),
        FLCCountryPhonesData(countryName: String(localized: "Бельгия"), phoneCode: "+32", phoneMask: "(XXX) XX-XX-XX", icon: UIImage(resource: .BGA), country: .belgium, countryCode: "BE"),
        FLCCountryPhonesData(countryName: String(localized: "Белиз"), phoneCode: "+501", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .BEL), country: .belize, countryCode: "BZ"),
        FLCCountryPhonesData(countryName: String(localized: "Бенин"), phoneCode: "+229", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .BEN), country: .benin, countryCode: "BJ"),
        FLCCountryPhonesData(countryName: String(localized: "Бермуды"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .BER), country: .bermuda, countryCode: "BM"),
        FLCCountryPhonesData(countryName: String(localized: "Бутан"), phoneCode: "+975", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .BUT), country: .bhutan, countryCode: "BT"),
        FLCCountryPhonesData(countryName: String(localized: "Боливия"), phoneCode: "+591", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .BOL), country: .bolivia, countryCode: "BO"),
        FLCCountryPhonesData(countryName: String(localized: "Босния и Герцеговина"), phoneCode: "+387", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .BHZ), country: .bosniaAndHerzegovina, countryCode: "BA"),
        FLCCountryPhonesData(countryName: String(localized: "Ботсвана"), phoneCode: "+267", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .BOT), country: .botswana, countryCode: "BW"),
        FLCCountryPhonesData(countryName: String(localized: "Бразилия"), phoneCode: "+55", phoneMask: "(XX) XXXXX-XXXX", icon: UIImage(resource: .BRA), country: .brazil, countryCode: "BR"),
        FLCCountryPhonesData(countryName: String(localized: "Британские Виргинские острова"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .BVI), country: .britishVirginIslands, countryCode: "VG"),
        FLCCountryPhonesData(countryName: String(localized: "Бруней"), phoneCode: "+673", phoneMask: "(XXX) XXXX", icon: UIImage(resource: .BRU), country: .brunei, countryCode: "BN"),
        FLCCountryPhonesData(countryName: String(localized: "Болгария"), phoneCode: "+359", phoneMask: "(XXX) XXX-XXX", icon: UIImage(resource: .BLG), country: .bulgaria, countryCode: "BG"),
        FLCCountryPhonesData(countryName: String(localized: "Буркина-Фасо"), phoneCode: "+226", phoneMask: "(XX) XX-XX-XX-XX", icon: UIImage(resource: .BUR), country: .burkinaFaso, countryCode: "BF"),
        FLCCountryPhonesData(countryName: String(localized: "Камбоджа"), phoneCode: "+855", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .KAM), country: .cambodia, countryCode: "KH"),
        FLCCountryPhonesData(countryName: String(localized: "Камерун"), phoneCode: "+237", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .CAM), country: .cameroon, countryCode: "CM"),
        FLCCountryPhonesData(countryName: String(localized: "Канада"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .CAN), country: .canada, countryCode: "CA"),
        FLCCountryPhonesData(countryName: String(localized: "Кабо-Верде"), phoneCode: "+238", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .CAB), country: .capeVerde, countryCode: "CV"),
        FLCCountryPhonesData(countryName: String(localized: "Каймановы острова"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .KAI), country: .caymanIslands, countryCode: "KY"),
        FLCCountryPhonesData(countryName: String(localized: "Чад"), phoneCode: "+235", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .CHD), country: .chad, countryCode: "TD"),
        FLCCountryPhonesData(countryName: String(localized: "Чили"), phoneCode: "+56", phoneMask: "(X) XXXX-XXXX", icon: UIImage(resource: .CHI), country: .chile, countryCode: "CL"),
        FLCCountryPhonesData(countryName: String(localized: "Китай"), phoneCode: "+86", phoneMask: "(XXX) XXXX-XXXX", icon: UIImage(resource: .CHA), country: .china, countryCode: "CN"),
        FLCCountryPhonesData(countryName: String(localized: "Колумбия"), phoneCode: "+57", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .COL), country: .colombia, countryCode: "CO"),
        FLCCountryPhonesData(countryName: String(localized: "Демократическая Республика Конго"), phoneCode: "+243", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .COR), country: .democraticRepublicOfCongo, countryCode: "CD"),
        FLCCountryPhonesData(countryName: String(localized: "Республика Конго"), phoneCode: "+242", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .COR), country: .republicOfCongo, countryCode: "CG"),
        FLCCountryPhonesData(countryName: String(localized: "Коста-Рика"), phoneCode: "+506", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .CRC), country: .costaRica, countryCode: "CR"),
        FLCCountryPhonesData(countryName: String(localized: "Кот-д’Ивуар"), phoneCode: "+225", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .CIV), country: .coteDIvoire, countryCode: "CI"),
        FLCCountryPhonesData(countryName: String(localized: "Хорватия"), phoneCode: "+385", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .HOR), country: .croatia, countryCode: "HR"),
        FLCCountryPhonesData(countryName: String(localized: "Кипр"), phoneCode: "+357", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .CYP), country: .cyprus, countryCode: "CY"),
        FLCCountryPhonesData(countryName: String(localized: "Чехия"), phoneCode: "+420", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .CHE), country: .czechRepublic, countryCode: "CZ"),
        FLCCountryPhonesData(countryName: String(localized: "Дания"), phoneCode: "+45", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .DEN), country: .denmark, countryCode: "DK"),
        FLCCountryPhonesData(countryName: String(localized: "Доминика"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .DMN), country: .dominica, countryCode: "DM"),
        FLCCountryPhonesData(countryName: String(localized: "Доминиканская Республика"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .DOM), country: .dominicanRepublic, countryCode: "DO"),
        FLCCountryPhonesData(countryName: String(localized: "Эквадор"), phoneCode: "+593", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .ECU), country: .ecuador, countryCode: "EC"),
        FLCCountryPhonesData(countryName: String(localized: "Египет"), phoneCode: "+20", phoneMask: "(XXXX) XXX-XXX", icon: UIImage(resource: .EGY), country: .egypt, countryCode: "EG"),
        FLCCountryPhonesData(countryName: String(localized: "Сальвадор"), phoneCode: "+503", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .SAL), country: .elSalvador, countryCode: "SV"),
        FLCCountryPhonesData(countryName: String(localized: "Эстония"), phoneCode: "+372", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .EST), country: .estonia, countryCode: "EE"),
        FLCCountryPhonesData(countryName: String(localized: "Эсватини"), phoneCode: "+268", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .ESW), country: .eswatini, countryCode: "SZ"),
        FLCCountryPhonesData(countryName: String(localized: "Фиджи"), phoneCode: "+679", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .FIJ), country: .fiji, countryCode: "FJ"),
        FLCCountryPhonesData(countryName: String(localized: "Финляндия"), phoneCode: "+358", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .FIN), country: .finland, countryCode: "FI"),
        FLCCountryPhonesData(countryName: String(localized: "Франция"), phoneCode: "+33", phoneMask: "(X) XX-XX-XX-XX", icon: UIImage(resource: .FRA), country: .france, countryCode: "FR"),
        FLCCountryPhonesData(countryName: String(localized: "Габон"), phoneCode: "+241", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .GAB), country: .gabon, countryCode: "GA"),
        FLCCountryPhonesData(countryName: String(localized: "Гамбия"), phoneCode: "+220", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .GAM), country: .gambia, countryCode: "GM"),
        FLCCountryPhonesData(countryName: String(localized: "Грузия"), phoneCode: "+995", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GEO), country: .georgia, countryCode: "GE"),
        FLCCountryPhonesData(countryName: String(localized: "Германия"), phoneCode: "+49", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GER), country: .germany, countryCode: "DE"),
        FLCCountryPhonesData(countryName: String(localized: "Гана"), phoneCode: "+233", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GHA), country: .ghana, countryCode: "GH"),
        FLCCountryPhonesData(countryName: String(localized: "Греция"), phoneCode: "+30", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GRE), country: .greece, countryCode: "GR"),
        FLCCountryPhonesData(countryName: String(localized: "Гренада"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GRN), country: .grenada, countryCode: "GD"),
        FLCCountryPhonesData(countryName: String(localized: "Гватемала"), phoneCode: "+502", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .GUA), country: .guatemala, countryCode: "GT"),
        FLCCountryPhonesData(countryName: String(localized: "Гвинея-Бисау"), phoneCode: "+245", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GUI), country: .guineaBissau, countryCode: "GW"),
        FLCCountryPhonesData(countryName: String(localized: "Гайана"), phoneCode: "+592", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GAI), country: .guyana, countryCode: "GY"),
        FLCCountryPhonesData(countryName: String(localized: "Гондурас"), phoneCode: "+504", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .HON), country: .honduras, countryCode: "HN"),
        FLCCountryPhonesData(countryName: String(localized: "Гонконг"), phoneCode: "+852", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .HNK), country: .hongKong, countryCode: "HK"),
        FLCCountryPhonesData(countryName: String(localized: "Венгрия"), phoneCode: "+36", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .HUN), country: .hungary, countryCode: "HU"),
        FLCCountryPhonesData(countryName: String(localized: "Исландия"), phoneCode: "+354", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ISL), country: .iceland, countryCode: "IS"),
        FLCCountryPhonesData(countryName: String(localized: "Индия"), phoneCode: "+91", phoneMask: "(XXXXX) XXXXX", icon: UIImage(resource: .IND), country: .india, countryCode: "IN"),
        FLCCountryPhonesData(countryName: String(localized: "Индонезия"), phoneCode: "+62", phoneMask: "(XXX) XXXX-XXXX", icon: UIImage(resource: .INS), country: .indonesia, countryCode: "ID"),
        FLCCountryPhonesData(countryName: String(localized: "Ирак"), phoneCode: "+964", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .IRK), country: .iraq, countryCode: "IQ"),
        FLCCountryPhonesData(countryName: String(localized: "Ирландия"), phoneCode: "+353", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .IRL), country: .ireland, countryCode: "IE"),
        FLCCountryPhonesData(countryName: String(localized: "Израиль"), phoneCode: "+972", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .ISR), country: .israel, countryCode: "IL"),
        FLCCountryPhonesData(countryName: String(localized: "Италия"), phoneCode: "+39", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ITA), country: .italy, countryCode: "IT"),
        FLCCountryPhonesData(countryName: String(localized: "Ямайка"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .JAM), country: .jamaica, countryCode: "JM"),
        FLCCountryPhonesData(countryName: String(localized: "Япония"), phoneCode: "+81", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .JAP), country: .japan, countryCode: "JP"),
        FLCCountryPhonesData(countryName: String(localized: "Иордания"), phoneCode: "+962", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .JOR), country: .jordan, countryCode: "JO"),
        FLCCountryPhonesData(countryName: String(localized: "Кения"), phoneCode: "+254", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .KEN), country: .kenya, countryCode: "KE"),
        FLCCountryPhonesData(countryName: String(localized: "Республика Корея"), phoneCode: "+82", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .KOR), country: .republicOfKorea, countryCode: "KR"),
        FLCCountryPhonesData(countryName: String(localized: "Косово"), phoneCode: "+383", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .KOS), country: .kosovo, countryCode: "XK"),
        FLCCountryPhonesData(countryName: String(localized: "Кувейт"), phoneCode: "+965", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .KUW), country: .kuwait, countryCode: "KW"),
        FLCCountryPhonesData(countryName: String(localized: "Кыргызстан"), phoneCode: "+996", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .KYR), country: .kyrgyzstan, countryCode: "KG"),
        FLCCountryPhonesData(countryName: String(localized: "Лаос"), phoneCode: "+856", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .LAO), country: .laos, countryCode: "LA"),
        FLCCountryPhonesData(countryName: String(localized: "Латвия"), phoneCode: "+371", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .LAT), country: .latvia, countryCode: "LV"),
        FLCCountryPhonesData(countryName: String(localized: "Ливан"), phoneCode: "+961", phoneMask: "(XXX) XXX-XXX", icon: UIImage(resource: .LIV), country: .lebanon, countryCode: "LB"),
        FLCCountryPhonesData(countryName: String(localized: "Либерия"), phoneCode: "+231", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .LIB), country: .liberia, countryCode: "LR"),
        FLCCountryPhonesData(countryName: String(localized: "Ливия"), phoneCode: "+218", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .LIA), country: .libya, countryCode: "LY"),
        FLCCountryPhonesData(countryName: String(localized: "Литва"), phoneCode: "+370", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .LIT), country: .lithuania, countryCode: "LT"),
        FLCCountryPhonesData(countryName: String(localized: "Люксембург"), phoneCode: "+352", phoneMask: "(XXX) XXX-XXX", icon: UIImage(resource: .LUX), country: .luxembourg, countryCode: "LU"),
        FLCCountryPhonesData(countryName: String(localized: "Макао"), phoneCode: "+853", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MAK), country: .macao, countryCode: "MO"),
        FLCCountryPhonesData(countryName: String(localized: "Мадагаскар"), phoneCode: "+261", phoneMask: "(XX) XXX-XX-XX", icon: UIImage(resource: .MAD), country: .madagascar, countryCode: "MG"),
        FLCCountryPhonesData(countryName: String(localized: "Малави"), phoneCode: "+265", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MAL), country: .malawi, countryCode: "MW"),
        FLCCountryPhonesData(countryName: String(localized: "Малайзия"), phoneCode: "+60", phoneMask: "(X) XXXX-XXXX", icon: UIImage(resource: .MAZ), country: .malaysia, countryCode: "MY"),
        FLCCountryPhonesData(countryName: String(localized: "Мальдивы"), phoneCode: "+960", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MLD), country: .maldives, countryCode: "MV"),
        FLCCountryPhonesData(countryName: String(localized: "Мали"), phoneCode: "+223", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MLI), country: .mali, countryCode: "ML"),
        FLCCountryPhonesData(countryName: String(localized: "Мальта"), phoneCode: "+356", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .MLT), country: .malta, countryCode: "MT"),
        FLCCountryPhonesData(countryName: String(localized: "Мавритания"), phoneCode: "+222", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .MAV), country: .mauritania, countryCode: "MR"),
        FLCCountryPhonesData(countryName: String(localized: "Маврикий"), phoneCode: "+230", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MAR), country: .mauritius, countryCode: "MU"),
        FLCCountryPhonesData(countryName: String(localized: "Мексика"), phoneCode: "+52", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MEX), country: .mexico, countryCode: "MX"),
        FLCCountryPhonesData(countryName: String(localized: "Микронезия"), phoneCode: "+691", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MIC), country: .micronesia, countryCode: "FM"),
        FLCCountryPhonesData(countryName: String(localized: "Молдова"), phoneCode: "+373", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MOL), country: .moldova, countryCode: "MD"),
        FLCCountryPhonesData(countryName: String(localized: "Монголия"), phoneCode: "+976", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .MON), country: .mongolia, countryCode: "MN"),
        FLCCountryPhonesData(countryName: String(localized: "Черногория"), phoneCode: "+382", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .MNT), country: .montenegro, countryCode: "ME"),
        FLCCountryPhonesData(countryName: String(localized: "Монтсеррат"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MTS), country: .montserrat, countryCode: "MS"),
        FLCCountryPhonesData(countryName: String(localized: "Марокко"), phoneCode: "+212", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MRC), country: .morocco, countryCode: "MA"),
        FLCCountryPhonesData(countryName: String(localized: "Мозамбик"), phoneCode: "+258", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .MOZ), country: .mozambique, countryCode: "MZ"),
        FLCCountryPhonesData(countryName: String(localized: "Мьянма"), phoneCode: "+95", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MYA), country: .myanmar, countryCode: "MM"),
        FLCCountryPhonesData(countryName: String(localized: "Намибия"), phoneCode: "+264", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .NAM), country: .namibia, countryCode: "NA"),
        FLCCountryPhonesData(countryName: String(localized: "Науру"), phoneCode: "+674", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .NAU), country: .nauru, countryCode: "NR"),
        FLCCountryPhonesData(countryName: String(localized: "Непал"), phoneCode: "+977", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .NEP), country: .nepal, countryCode: "NP"),
        FLCCountryPhonesData(countryName: String(localized: "Нидерланды"), phoneCode: "+31", phoneMask: "(XXX) XX-XX-XX", icon: UIImage(resource: .NET), country: .netherlands, countryCode: "NL"),
        FLCCountryPhonesData(countryName: String(localized: "Новая Зеландия"), phoneCode: "+64", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .NZN), country: .newZealand, countryCode: "NZ"),
        FLCCountryPhonesData(countryName: String(localized: "Никарагуа"), phoneCode: "+505", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .NIC), country: .nicaragua, countryCode: "NI"),
        FLCCountryPhonesData(countryName: String(localized: "Нигер"), phoneCode: "+227", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .NGR), country: .niger, countryCode: "NE"),
        FLCCountryPhonesData(countryName: String(localized: "Нигерия"), phoneCode: "+234", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .NIG), country: .nigeria, countryCode: "NG"),
        FLCCountryPhonesData(countryName: String(localized: "Северная Македония"), phoneCode: "+389", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .MKD), country: .northMacedonia, countryCode: "MK"),
        FLCCountryPhonesData(countryName: String(localized: "Норвегия"), phoneCode: "+47", phoneMask: "(XX) XX-XX-XX-XX", icon: UIImage(resource: .NOR), country: .norway, countryCode: "NO"),
        FLCCountryPhonesData(countryName: String(localized: "Оман"), phoneCode: "+968", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .OMA), country: .oman, countryCode: "OM"),
        FLCCountryPhonesData(countryName: String(localized: "Пакистан"), phoneCode: "+92", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .PAK), country: .pakistan, countryCode: "PK"),
        FLCCountryPhonesData(countryName: String(localized: "Палау"), phoneCode: "+680", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .PAL), country: .palau, countryCode: "PW"),
        FLCCountryPhonesData(countryName: String(localized: "Панама"), phoneCode: "+507", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .PAN), country: .panama, countryCode: "PA"),
        FLCCountryPhonesData(countryName: String(localized: "Папуа-Новая Гвинея"), phoneCode: "+675", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .PAP), country: .papuaNewGuinea, countryCode: "PG"),
        FLCCountryPhonesData(countryName: String(localized: "Парагвай"), phoneCode: "+595", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .PAR), country: .paraguay, countryCode: "PY"),
        FLCCountryPhonesData(countryName: String(localized: "Перу"), phoneCode: "+51", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .PER), country: .peru, countryCode: "PE"),
        FLCCountryPhonesData(countryName: String(localized: "Филиппины"), phoneCode: "+63", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .PHI), country: .philippines, countryCode: "PH"),
        FLCCountryPhonesData(countryName: String(localized: "Польша"), phoneCode: "+48", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .POL), country: .poland, countryCode: "PL"),
        FLCCountryPhonesData(countryName: String(localized: "Португалия"), phoneCode: "+351", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .POR), country: .portugal, countryCode: "PT"),
        FLCCountryPhonesData(countryName: String(localized: "Катар"), phoneCode: "+974", phoneMask: "(XXXXX) XXXXX", icon: UIImage(resource: .QAT), country: .qatar, countryCode: "QA"),
        FLCCountryPhonesData(countryName: String(localized: "Румыния"), phoneCode: "+40", phoneMask: "(XXX) XXXX-XXXX", icon: UIImage(resource: .ROM), country: .romania, countryCode: "RO"),
        FLCCountryPhonesData(countryName: String(localized: "Руанда"), phoneCode: "+250", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .RWA), country: .rwanda, countryCode: "RW"),
        FLCCountryPhonesData(countryName: String(localized: "Сан-Томе и Принсипи"), phoneCode: "+239", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .SAN), country: .saoTomeAndPrincipe, countryCode: "ST"),
        FLCCountryPhonesData(countryName: String(localized: "Саудовская Аравия"), phoneCode: "+966", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .SAU), country: .saudiArabia, countryCode: "SA"),
        FLCCountryPhonesData(countryName: String(localized: "Сенегал"), phoneCode: "+221", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .SEN), country: .senegal, countryCode: "SN"),
        FLCCountryPhonesData(countryName: String(localized: "Сербия"), phoneCode: "+381", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .SER), country: .serbia, countryCode: "RS"),
        FLCCountryPhonesData(countryName: String(localized: "Сейшелы"), phoneCode: "+248", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .SEY), country: .seychelles, countryCode: "SC"),
        FLCCountryPhonesData(countryName: String(localized: "Сьерра-Леоне"), phoneCode: "+232", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .SIE), country: .sierraLeone, countryCode: "SL"),
        FLCCountryPhonesData(countryName: String(localized: "Сингапур"), phoneCode: "+65", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .SIN), country: .singapore, countryCode: "SG"),
        FLCCountryPhonesData(countryName: String(localized: "Словакия"), phoneCode: "+421", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .SVK), country: .slovakia, countryCode: "SK"),
        FLCCountryPhonesData(countryName: String(localized: "Словения"), phoneCode: "+386", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .SLV), country: .slovenia, countryCode: "SI"),
        FLCCountryPhonesData(countryName: String(localized: "Соломоновы острова"), phoneCode: "+677", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .SOL), country: .solomonIslands, countryCode: "SB"),
        FLCCountryPhonesData(countryName: String(localized: "Южная Африка"), phoneCode: "+27", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .UAR), country: .southAfrica, countryCode: "ZA"),
        FLCCountryPhonesData(countryName: String(localized: "Испания"), phoneCode: "+34", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .SPA), country: .spain, countryCode: "ES"),
        FLCCountryPhonesData(countryName: String(localized: "Шри-Ланка"), phoneCode: "+94", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .SHR), country: .sriLanka, countryCode: "LK"),
        FLCCountryPhonesData(countryName: String(localized: "Сент-Китс и Невис"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXX", icon: UIImage(resource: .SKN), country: .saintKittsAndNevis, countryCode: "KN"),
        FLCCountryPhonesData(countryName: String(localized: "Сент-Люсия"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .STL), country: .saintLucia, countryCode: "LC"),
        FLCCountryPhonesData(countryName: String(localized: "Сент-Винсент и Гренадины"), phoneCode: "+1", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .SVG), country: .saintVincentAndTheGrenadines, countryCode: "VC"),
        FLCCountryPhonesData(countryName: String(localized: "Суринам"), phoneCode: "+597", phoneMask: "(XXXX) XXXX", icon: UIImage(resource: .SUR), country: .suriname, countryCode: "SR"),
        FLCCountryPhonesData(countryName: String(localized: "Швеция"), phoneCode: "+46", phoneMask: "(XXX) XXX-XXX", icon: UIImage(resource: .SWE), country: .sweden, countryCode: "SE"),
        FLCCountryPhonesData(countryName: String(localized: "Швейцария"), phoneCode: "+41", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .SWI), country: .switzerland, countryCode: "CH"),
        FLCCountryPhonesData(countryName: String(localized: "Тайвань"), phoneCode: "+886", phoneMask: "(XX) XXX-XX-XX", icon: UIImage(resource: .TAI), country: .taiwan, countryCode: "TW"),
        FLCCountryPhonesData(countryName: String(localized: "Таджикистан"), phoneCode: "+992", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .TAD), country: .tajikistan, countryCode: "TJ"),
        FLCCountryPhonesData(countryName: String(localized: "Танзания"), phoneCode: "+255", phoneMask: "(X) XXXX-XXXX", icon: UIImage(resource: .TAN), country: .tanzania, countryCode: "TZ"),
        FLCCountryPhonesData(countryName: String(localized: "Таиланд"), phoneCode: "+66", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .THL), country: .thailand, countryCode: "TH"),
        FLCCountryPhonesData(countryName: String(localized: "Тонга"), phoneCode: "+676", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .TON), country: .tonga, countryCode: "TO"),
        FLCCountryPhonesData(countryName: String(localized: "Тринидад и Тобаго"), phoneCode: "+1", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .TIT), country: .trinidadAndTobago, countryCode: "TT"),
        FLCCountryPhonesData(countryName: String(localized: "Тунис"), phoneCode: "+216", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .TUN), country: .tunisia, countryCode: "TN"),
        FLCCountryPhonesData(countryName: String(localized: "Турция"), phoneCode: "+90", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .TUR), country: .turkey, countryCode: "TR"),
        FLCCountryPhonesData(countryName: String(localized: "Туркменистан"), phoneCode: "+993", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .TRK), country: .turkmenistan, countryCode: "TM"),
        FLCCountryPhonesData(countryName: String(localized: "Теркс и Кайкос"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .TAC), country: .turksAndCaicos, countryCode: "TC"),
        FLCCountryPhonesData(countryName: String(localized: "Уганда"), phoneCode: "+256", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .UGA), country: .uganda, countryCode: "UG"),
        FLCCountryPhonesData(countryName: String(localized: "Украина"), phoneCode: "+380", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .UKR), country: .ukraine, countryCode: "UA"),
        FLCCountryPhonesData(countryName: String(localized: "Объединенные Арабские Эмираты"), phoneCode: "+971", phoneMask: "(XX) XX-XX-XX", icon: UIImage(resource: .OAE), country: .unitedArabEmirates, countryCode: "AE"),
        FLCCountryPhonesData(countryName: String(localized: "Великобритания"), phoneCode: "+44", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .GBR), country: .unitedKingdom, countryCode: "GB"),
        FLCCountryPhonesData(countryName: String(localized: "Соединенные Штаты"), phoneCode: "+1", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .USA), country: .unitedStates, countryCode: "US"),
        FLCCountryPhonesData(countryName: String(localized: "Уругвай"), phoneCode: "+598", phoneMask: "(XX) XXX-XXX", icon: UIImage(resource: .URU), country: .uruguay, countryCode: "UY"),
        FLCCountryPhonesData(countryName: String(localized: "Узбекистан"), phoneCode: "+998", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .UZB), country: .uzbekistan, countryCode: "UZ"),
        FLCCountryPhonesData(countryName: String(localized: "Вануату"), phoneCode: "+678", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .VAN), country: .vanuatu, countryCode: "VU"),
        FLCCountryPhonesData(countryName: String(localized: "Венесуэла"), phoneCode: "+58", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .VEN), country: .venezuela, countryCode: "VE"),
        FLCCountryPhonesData(countryName: String(localized: "Вьетнам"), phoneCode: "+84", phoneMask: "(XX) XXX-XXXX", icon: UIImage(resource: .VET), country: .vietnam, countryCode: "VN"),
        FLCCountryPhonesData(countryName: String(localized: "Йемен"), phoneCode: "+967", phoneMask: "(XXX) XX-XX-XX", icon: UIImage(resource: .YEM), country: .yemen, countryCode: "YE"),
        FLCCountryPhonesData(countryName: String(localized: "Замбия"), phoneCode: "+260", phoneMask: "(XX) XXXX-XXXX", icon: UIImage(resource: .ZAM), country: .zambia, countryCode: "ZM"),
        FLCCountryPhonesData(countryName: String(localized: "Зимбабве"), phoneCode: "+263", phoneMask: "(XXX) XXX-XXXX", icon: UIImage(resource: .ZIM), country: .zimbabwe, countryCode: "ZW")
    ]
    
    static let currencyOptions = [
        FLCPickerItem(title: CurrencyOptionsStrings.rublesShort, subtitle: CurrencyOptionsStrings.rubles, image: UIImage(named: CurrencyOptionsStrings.rublesShort)),
        FLCPickerItem(title: CurrencyOptionsStrings.yuanShort, subtitle: CurrencyOptionsStrings.yuan, image: UIImage(named: CurrencyOptionsStrings.yuanShort)),
        FLCPickerItem(title: CurrencyOptionsStrings.lirasShort, subtitle: CurrencyOptionsStrings.liras, image: UIImage(named: CurrencyOptionsStrings.lirasShort)),
        FLCPickerItem(title: CurrencyOptionsStrings.dollarsShort, subtitle: CurrencyOptionsStrings.dollars, image: UIImage(named: CurrencyOptionsStrings.dollarsShort)),
        FLCPickerItem(title: CurrencyOptionsStrings.euroShort, subtitle: CurrencyOptionsStrings.euro, image: UIImage(named: CurrencyOptionsStrings.euroShort))
    ]
    
    static let countriesOptions = [
        FLCPickerItem(title: FLCCountryOptionStrings.china, subtitle: "", image: UIImage(named: CurrencyOptionsStrings.yuanShort)),
        FLCPickerItem(title: FLCCountryOptionStrings.turkey, subtitle: "", image: UIImage(named: CurrencyOptionsStrings.lirasShort))
    ]
    
    static let chinaAirportsOptions = [
        FLCPickerItem(title: FLCCity.beijing.rawValue, subtitle: ChinaAirportsStrings.PKX, image: FLCIcon.plane.icon, isOpenForAdd: false),
        FLCPickerItem(title: FLCCity.shanghai.rawValue, subtitle: ChinaAirportsStrings.PVG, image: FLCIcon.plane.icon, isOpenForAdd: false),
        FLCPickerItem(title: FLCCity.guangzhou.rawValue, subtitle: ChinaAirportsStrings.CAN, image: FLCIcon.plane.icon, isOpenForAdd: false),
        FLCPickerItem(title: FLCCity.shenzhen.rawValue, subtitle: ChinaAirportsStrings.SZX, image: FLCIcon.plane.icon, isOpenForAdd: false)
    ]
    
    static let chinaDeliveryTypes = [
        FLCPickerItem(title: "EXW, " + FLCDeliveryTypeStrings.exwShipperClient, subtitle: FLCDeliveryTypeStrings.exwShipperClientComment, image: nil),
        FLCPickerItem(title: "EXW, " + FLCDeliveryTypeStrings.exwShipperPodolsk, subtitle: FLCDeliveryTypeStrings.exwShipperPodolskComment, image: nil),
        FLCPickerItem(title: "FCA, " + FLCDeliveryTypeStrings.fcaChinaWarehouseClient, subtitle: FLCDeliveryTypeStrings.fcaChinaWarehouseClientComment, image: nil),
        FLCPickerItem(title: "FCA, " + FLCDeliveryTypeStrings.fcaChinaWarehousePodolsk, subtitle: FLCDeliveryTypeStrings.fcaChinaWarehousePodolskComment, image: nil)
    ]
    
    static let turkeyDeliveryTypes = [
        FLCPickerItem(title: "EXW, " + FLCDeliveryTypeStrings.exwShipperClient, subtitle: FLCDeliveryTypeStrings.exwShipperClientComment, image: nil),
        FLCPickerItem(title: "EXW, " + FLCDeliveryTypeStrings.exwShipperPodolsk, subtitle: FLCDeliveryTypeStrings.exwShipperPodolskComment, image: nil),
        FLCPickerItem(title: "FCA, " + FLCDeliveryTypeStrings.fcaTurkeyWarehouseClient, subtitle: FLCDeliveryTypeStrings.fcaTurkeyWarehouseClientComment, image: nil),
        FLCPickerItem(title: "FCA, " + FLCDeliveryTypeStrings.fcaTurkeyWarehousePodolsk, subtitle: FLCDeliveryTypeStrings.fcaTurkeyWarehousePodolskComment, image: nil)
    ]
    
    static let defaultManager = FLCManager(
        id: 1,
        name: "Игорь Волков",
        position: "Менеджер по привлечению клиентов",
        mobilePhone: "8 (980) 800-21-24",
        landlinePhone: "8 (495) 640-63-55 доб. 609",
        telegram: "igorVolkovFLC",
        whatsapp: "7(980)-800-21-24",
        email: "i.volkov@free-lines.ru",
        avatarRef: "managerPhotos/igorVolkov.png",
        dataDate: "01.05.2024",
        avatarData: UIImage(named: "personPlaceholder")?.pngData()
    )
    
    static let defaultUsefulInfoDocuments: [Document] = [
        Document(title: "Шаблон договора", fileName: "documents/logisticsAgreement.docx", docDate: "12.05.2024"),
        Document(title: "Презентация FLC", fileName: "documents/presentationFLC.pdf", docDate: "12.05.2024"),
        Document(title: "Презентация по Китаю", fileName: "documents/presentationChina.pdf", docDate: "12.05.2024")
    ]
    
    static let defaultFacility = FLCFacility(
        latitude: 55.712170,
        longitude: 37.657890,
        name: "Центральный офис",
        address: "г. Москва, ул. Ленинская Слобода, 26с2 (м. Автозаводская)",
        workingHours: "пн-пт, с 9:30 до 18:30",
        phoneNumber: "+7 (495) 640-63-55",
        email: "mail@free-lines.com"
    )
}
