import Foundation

enum FLCError: String, Error {
    case unableToFetchCategories = "Ошибка при получении категорий"
    case invalidEndpoint = "Неправильный эндпоинт"
    case invalidResponce = "Неверный ответ от сервера"
    case invalidResponceString = "Неверная строка ответа"
    case invalidBubbleToken = "Токен Bubble недействителен или недоступен"
    case decodingError = "Ошибка декодирования данных"
    case unableToDownload = "Не удается загрузить данные"
    case invalidData = "Полученные с сервера данные недействительны"
    case unableToGetDocuments = "Эта коллекция не содержит документов"
    case castingError = "Значение не является строкой"
    case unableToFetchOrDecodeFromCoreData = "Не удалось получить или декодировать элементы из CoreData"
    case unableToEncodeOrSavetoCoreData = "Не удалось закодировать или сохранить элементы в CoreData"
    case unableToUpdateInCoreData = "Не удалось обновить элементы в CoreData"
    case entityNotFound = "Сущность не найдена"
    case unableToSaveToUserDefaults = "Не удалось сохранить элементы в UserDefaults"
    case unableToUpdateUserDefaults = "Не удалось обновить элементы в UserDefaults"
    case unableToRetrieveFromUserDefaults = "Не удалось извлечь элементы из UserDefaults"
    case unableToDeleteItemsInCoreData = "Не удалось удалить элементы в CoreData"
    case unknownFirebaseStorageError = "Произошла неизвестная ошибка в Firebase"
    case unableToAccessDirectory = "Не удается получить доступ к директории Documents"
    case errorGettingData = "Не удается преобразовать строку в данные"
    case errorWritingToFile = "Ошибка записи в файл"
    case errorDeletingFile = "Не удается удалить файл"
    case unableToFindContainerURL = "Не удалось найти URL контейнера для группы приложений"
    case unableToFindAppDirectory = "Не удалось найти директорию поддержки приложений"
    case unableToDecodeFromKeychain = "Не удалось декодировать элемент из Keychain"
    case unableToEncodeFromKeychain = "Не удалось закодировать элемент для Keychain"
}
